rule {rule_name}
{
    meta:
        description = "{description}"
        author = "Auto-generated by Threat Intel Analyzer"
        date = "{date}"
        hash = "{hash}"
        family = "{family}"
        confidence = "{confidence}"
        threat_level = "{threat_level}"
        reference = "{reference}"
        tags = "{tags}"
        
    strings:
{string_definitions}
        
    condition:
        {condition}
}
