version: '3.8'

services:
  # 主分析环境 - 包含大多数分析工具
  malware-analyst:
    build:
      context: ../dockerized
      dockerfile: Dockerfile
    container_name: malware-analyst
    volumes:
      - ../../samples:/analysis/samples:ro
      - ../../tools:/analysis/tools:ro
      - ../../reports:/analysis/reports
    networks:
      malnet:
        ipv4_address: 172.30.1.2
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    command: /bin/bash

  # 网络服务模拟 - 用于捕获勒索软件网络通信
  fakenet:
    build:
      context: .
      dockerfile: Dockerfile.fakenet
    container_name: fakenet
    ports:
      - "127.0.0.1:8080:80"      # HTTP 
      - "127.0.0.1:8443:443"     # HTTPS
      - "127.0.0.1:8053:53/udp"  # DNS
      - "127.0.0.1:8021:21"      # FTP
      - "127.0.0.1:8025:25"      # SMTP
    networks:
      malnet:
        ipv4_address: 172.30.1.3
    volumes:
      - ../../logs/network:/logs
    command: python3 -m fakenet.fakenet

  # 动态行为监控容器
  procmon:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: procmon
    volumes:
      - ../../samples:/samples:ro
      - ../../logs/monitor:/logs
    networks:
      malnet:
        ipv4_address: 172.30.1.4
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    command: /bin/bash

networks:
  malnet:
    driver: bridge
    internal: true  # 内部网络，不连接外网
    ipam:
      config:
        - subnet: 172.30.1.0/24
EOF < /dev/null